config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :photos
  get 'home/index'
  root 'home#index'
  get 'mypins' => 'photos#mypins'
  get 'pinsof/:user_id' => 'photos#pinsof', :as => "pinsof"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :url, presence: true;
  validates :description, presence: true

  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def mypins
    @photos = current_user.photos
  end

  def pinsof
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    @photos = @user.photos
  end

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|

      if @photo.save
        last_photo = Photo.last
        last_photo.update(user_id: current_user.id)
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:url, :description, :active, :user_id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/home/index.html.erb
<link rel="stylesheet" href="http://drive.google.com/uc?export=view&id=1Drs3hCZlnjvRoQ8iz0e4_yHifdDbsq5J">
<link href="http://drive.google.com/uc?export=view&id=17gs52PalC1dMxP-h8atpUDN4Tm3qRKOz" rel="stylesheet" />
<link href="http://drive.google.com/uc?export=view&id=1SEofBw3yTukJhf67pPRx2k9VcQjzJffu" rel="stylesheet" />
<link rel="stylesheet" href="http://drive.google.com/uc?export=view&id=1kf2DBk20EBYsqaOvaYCp3emPp-NvkNyh">
<link href="http://drive.google.com/uc?export=view&id=1t7fw6d-G6BZNwPgh4bSSAhLrbCE-ABZk" rel="stylesheet" />
<link rel="stylesheet" href="http://drive.google.com/uc?export=view&id=1eVRM0BF0Z74ISifOPJJCRPyLE_ceV_Ln">

<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,700,400' rel='stylesheet' type='text/css'>
<script src="http://drive.google.com/uc?export=view&id=1BsSOsFAGj3yay3si-yp5AXLiAeT1e3n-"></script>

<style>
  #hola {
    background-color:black;
    opacity: 0.5;
    size: 50px;
  }
   #intro{
     width: 100%;
     min-height: 100%;
     margin: 0 auto;
     background: rgb(230, 236, 236);
     box-shadow: 0px 0px 40px black;
     border-radius: 6px;
     box-sizing: border-box;
     overflow: hidden;

  }
</style>

<div id="intro">
  <ul id="slippry-slider">
    <li>
      <a href="#slide1"><img src="https://images.pexels.com/photos/34676/pexels-photo.jpg?w=1260&h=750&auto=compress&cs=tinysrgb"  alt="<p id='hola'>Welcome to ...</p>"></a>
    </li>
    <li>
      <a href="#slide2"><img src="https://images.pexels.com/photos/574077/pexels-photo-574077.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb"  alt="<img src='https://bgasparotto.com/wp-content/uploads/2016/03/ruby-logo.png' style='opacity: 0.5' width='100%'></img>"></a>

    </li>
    <li>
      <a href="#slide3"><img src="https://images.pexels.com/photos/273222/pexels-photo-273222.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb" alt="<p id='hola'>  Don't repeat yourself! <span class='red'>♥</span> :)</p>"></a>
    </li>
  </ul>
</div>
<!-- end intro -->

<a href="#" class="scrollup"><i class="fa fa-angle-up fa-2x"></i></a>
<!-- javascript -->
<script src="http://drive.google.com/uc?export=view&id=10NZZBMTI8GT_62S26lHdbi0CrM74V95Z"></script>
<script src="http://drive.google.com/uc?export=view&id=18vx65lCOaACT1onYyCtNB3JeX5sdQR6A"></script>
<script src="http://drive.google.com/uc?export=view&id=1Q2_GAl-FjuS2-Jg6oV90fiVpjTQz8hyo"></script>
<script src="http://drive.google.com/uc?export=view&id=1UN8NCp7Zllc3yIE7MrjSfVicv7aRgG2m"></script>
<script src="http://drive.google.com/uc?export=view&id=189AYrIr_q1MhlVegiF3z_2PNLUm0BC-R"></script>
<script src="http://drive.google.com/uc?export=view&id=1XtCf6qHXqD-IZA0QE2q94zMVBCY4IjqL"></script>
<script src="http://drive.google.com/uc?export=view&id=1NT5UaWB1L-IMb4ZprXLgpQhTcht0c0Nl"></script>
<script src="http://drive.google.com/uc?export=view&id=1I1fix-c3L0Oa9X9NWTQNbE0NM9CBOkCU"></script>
<script src="http://drive.google.com/uc?export=view&id=1k8BxWzgiSRsYjJcrD3AKgHIuFyQuLIxh"></script>
<script src="http://drive.google.com/uc?export=view&id=1ajWZelkCVTlGaJye8CT6JPLhZXxQ-Wb_"></script>
<script src="http://drive.google.com/uc?export=view&id=1dsvSZtpA2f-jW3VnPC2u1jIw-k--apFr"></script>
<script src="http://drive.google.com/uc?export=view&id=1BxVrmUTLK_nlk4MNnWdadRMrgx6tHQWj"></script>
<script src="http://drive.google.com/uc?export=view&id=1Ro3uTuxTapwv6zKqt3d81E7sf4pun9df"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD8HeI8o-c1NppZA-92oYlXakhDPYR7XMY"></script>
<script src="http://drive.google.com/uc?export=view&id=1i9lmHU55kiyM5vnOZauh89K7oDOrrr5_"></script>
<script>
    new AnimOnScroll(document.getElementById('grid'), {
        minDuration: 0.4,
        maxDuration: 0.7,
        viewportFactor: 0.2
    });
</script>
<script>
    $(document).ready(function() {
        $('#slippry-slider').slippry(
            defaults = {
                transition: 'vertical',
                useCSS: true,
                speed: 5000,
                pause: 3000,
                initSingle: false,
                auto: true,
                preload: 'visible',
                pager: false,
            }

        )
    });
</script>

<script src="http://drive.google.com/uc?export=view&id=11Pu03UocPFRjgIwSEteufrkzzdz305Vr"></script>







app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Pin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      body {
        margin: 0;
        font-size: 28px;
        background-image: url(https://dl.dropboxusercontent.com/s/fl40dtf554u6m2g/cover.jpg?dl=0);

      }

      .header {
        background-color: #f1f1f1;
        padding: 30px;
        text-align: center;
      }

      #navbar {
        overflow: hidden;
        background-color: #333;
      }

      #navbar a {
        float: left;
        display: block;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
      }

      #navbar a:hover {
        background-color: #ddd;
        color: black;
      }

      #navbar a.active {
        background-color: #0489B1;
        color: white;
      }

      .content {
        padding: 16px;
      }

      .sticky {
        position: fixed;
        top: 0;
        width: 100%
      }

      .sticky + .content {
        padding-top: 60px;
      }
    </style>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body background="https://theresortgroupplc.com/wp-content/uploads/2016/12/shutterstock_245476081resized.jpg">
    <div id="navbar">
    <a class="active" href="<%= root_path %>">Home <img src="http://s966.info/library/h/home-icon-png-white/home-icon-png-white-03.png" style="width:25px"/> </a>
    <a href="<%= photos_path %>">Pins <img src="http://files.softicons.com/download/system-icons/windows-8-metro-invert-icons-by-dakirby309/png/256x256/Other/Pin.png" style="width:25px"></img> </a>
    <a href="<%= mypins_path %>">My Pins <img src="http://files.softicons.com/download/system-icons/windows-8-metro-invert-icons-by-dakirby309/png/256x256/Other/Pin.png" style="width:25px"></img> </a>
    <% if current_user.nil? %>
    <a class="navbar-right" href="<%= new_user_session_path %>">   Log In <img src="https://cdn1.iconfinder.com/data/icons/unique-round-blue/93/user-512.png" style="width:25px"></img> </a>

    <a class="navbar-right" href="<%= new_user_registration_path %>">  Sign up <img src="http://www.ymcaswkansas.org/sites/ymcaswkansas.oneeach.org/files/civicrm/friend.png" style="width:25px"/>   </a>
    
    
    <% else %>
    <a class="navbar-right" href="<%= destroy_user_session_path %>" data-method="delete"><img src="http://www.clker.com/cliparts/4/8/K/S/j/6/exit-button-hi.png" style="width:25px" alt="Exit" title="Exit"> <%= current_user.email %>  </a>
    <% end %>
    
        </div>
  <div class="container" style=" width: 70%;
  min-height: 100%;
  margin: 0 auto;
  background: rgb(230, 236, 236);
  box-shadow: 0px 0px 40px black;
  border-radius: 6px;
  box-sizing: border-box;
  overflow: hidden;">
  <!-- /About -->

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>


  </div>
  </body>

  <script>
      window.onscroll = function() {myFunction()};

      var navbar = document.getElementById("navbar");
      var sticky = navbar.offsetTop;

      function myFunction() {
          if (window.pageYOffset >= sticky) {
              navbar.classList.add("sticky")
          } else {
              navbar.classList.remove("sticky");
          }
      }
  </script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.1/masonry.pkgd.js">

</script>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :photo_url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :photo_description %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :photo_active %>
  </div>

  <div class="field">
    <%= form.label :user_id, hidden:true %>
    <%= form.text_field :user_id, :value => current_user.id,hidden:true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to image_tag('https://cdn2.iconfinder.com/data/icons/picons-essentials/71/visibility-512.png',:style=>'width:50px'), @photo %> |
<%= link_to image_tag('http://icons.iconarchive.com/icons/graphicloads/100-flat-2/256/arrow-back-icon.png',:style=>'width:50px'), photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>
<div id="grid">
<table class="table table-hover">
  <thead>
  <tr class="grid-item" style="width: 25%">
      <td>
        <% if user_signed_in? %>
           <%= link_to image_tag('http://icons.iconarchive.com/icons/custom-icon-design/flatastic-1/512/add-1-icon.png',:style=>'width:50px'), new_photo_path %>
        <% end %>
      <td>
  </tr>
    <tr class="grid-item" style="width: 25%">
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th>Active</th>
      <th>Created By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody align="center">
    <% @photos.each do |photo| %>
      <tr class="grid-item" style="width: 25%">
        <td><%= photo.name %></td>

        <td ><%= image_tag(photo.url, :style=>'width:200px') %></td>
        <td><%= photo.description %></td>
        <td><%= if(photo.active)then image_tag('https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Button_Icon_Green.svg/1024px-Button_Icon_Green.svg.png',:style=>'width:30px') else image_tag('http://www.urltarget.com/images/red-green-icon-blue-simple-glossy-circle-cartoon.png',:style=>'width:30px') end %></td>
        <td><%= photo.user_id %></td>
        <td><%= link_to image_tag('https://cdn2.iconfinder.com/data/icons/picons-essentials/71/visibility-512.png',:style=>'width:50px'), photo %></td>
        <% if !current_user.nil? %>
        <td><%= link_to image_tag('https://cdn1.iconfinder.com/data/icons/hawcons/32/698873-icon-136-document-edit-512.png',:style=>'width:50px'), edit_photo_path(photo) %></td>
        <td><%= link_to image_tag('http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/sign-delete-icon.png',:style=>'width:50px'), photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
          </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<
<script type="text/javascript" charset="utf-8">
    $('.grid').masonry({
        // options
        itemSelector: '.grid-item',
        columnWidth: 200
    });
    $(window).load(function () {
      $('.grid').masonry({
          // options
          itemSelector: '.grid-item',
          columnWidth: 200
      });
  })

</script>

app/views/photos/mypins.html.erb
<p id="notice"><%= notice %></p>

<h1>My Pins</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <td>
      <% if user_signed_in? %>
        <%= link_to image_tag('http://icons.iconarchive.com/icons/custom-icon-design/flatastic-1/512/add-1-icon.png',:style=>'width:50px'), new_photo_path %>
      <% end %>
    <td>
  </tr>
  <tr>
    <th>Url</th>
    <th>Description</th>
    <th>Active</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody align="center">
  <% @photos.each do |photo| %>
    <tr>
      <td ><%= image_tag(photo.url, :style=>'width:200px') %></td>
      <td><%= photo.description %></td>
      <td><%= if(photo.active)then image_tag('https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Button_Icon_Green.svg/1024px-Button_Icon_Green.svg.png',:style=>'width:30px') else image_tag('http://www.urltarget.com/images/red-green-icon-blue-simple-glossy-circle-cartoon.png',:style=>'width:30px') end %></td>
      <td><%= link_to image_tag('https://cdn2.iconfinder.com/data/icons/picons-essentials/71/visibility-512.png',:style=>'width:50px'), photo %></td>
      <% if !current_user.nil? %>
        <td><%= link_to image_tag('https://cdn1.iconfinder.com/data/icons/hawcons/32/698873-icon-136-document-edit-512.png',:style=>'width:50px'), edit_photo_path(photo) %></td>
        <td><%= link_to image_tag('http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/sign-delete-icon.png',:style=>'width:50px'), photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>



app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to image_tag('http://icons.iconarchive.com/icons/graphicloads/100-flat-2/256/arrow-back-icon.png',:style=>'width:50px'), photos_path %>

app/views/photos/pinsof.html.erb
<%= @user_id %>
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <td>
      <% if user_signed_in? %>
        <%= link_to image_tag('http://icons.iconarchive.com/icons/custom-icon-design/flatastic-1/512/add-1-icon.png',:style=>'width:50px'), new_photo_path %>
      <% end %>
    <td>
  </tr>
  <tr>
    <th>Url</th>
    <th>Description</th>
    <th>Active</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody align="center">
  <% @photos.each do |photo| %>
    <tr>
      <td ><%= image_tag(photo.url, :style=>'width:200px') %></td>
      <td><%= photo.description %></td>
      <td><%= if(photo.active)then image_tag('https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Button_Icon_Green.svg/1024px-Button_Icon_Green.svg.png',:style=>'width:30px') else image_tag('http://www.urltarget.com/images/red-green-icon-blue-simple-glossy-circle-cartoon.png',:style=>'width:30px') end %></td>
      <td><%= link_to image_tag('https://cdn2.iconfinder.com/data/icons/picons-essentials/71/visibility-512.png',:style=>'width:50px'), photo %></td>
      <% if !current_user.nil? %>
        <td><%= link_to image_tag('https://cdn1.iconfinder.com/data/icons/hawcons/32/698873-icon-136-document-edit-512.png',:style=>'width:50px'), edit_photo_path(photo) %></td>
        <td><%= link_to image_tag('http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/sign-delete-icon.png',:style=>'width:50px'), photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>



app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>
<table>
<tr>

  <td>
    <strong>Name:</strong>
    <%= @photo.name %>
  </td>
    <td>
    
    <strong>Url:</strong>
    <%= image_tag(@photo.url,:style=>'width:200px') %>
    </td>
    <td>
    <strong>Description:</strong>
    <%= @photo.description %>
    </td>
    <td>
    <strong>Active:</strong>
    <%= @photo.active %>
    </td>
</tr>
</table>




<%= link_to image_tag('https://cdn1.iconfinder.com/data/icons/hawcons/32/698873-icon-136-document-edit-512.png',:style=>'width:50px'), edit_photo_path(@photo) %> |
<%= link_to image_tag('http://icons.iconarchive.com/icons/graphicloads/100-flat-2/256/arrow-back-icon.png',:style=>'width:50px'), photos_path %>

<%= link_to 'Mas pins del mismo usuario', pinsof_path(@photo.user_id) %>